// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQYLTDXlaJa5lvgHRSJUZsm8bcDq25fo',
    appId: '1:802136451096:web:c0368b8cfad0a5223d7b6d',
    messagingSenderId: '802136451096',
    projectId: 'couponchecker-406307',
    authDomain: 'couponchecker-406307.firebaseapp.com',
    storageBucket: 'couponchecker-406307.appspot.com',
    measurementId: 'G-L6EQN17RLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJF3PdfvcrUQf730ucEKWK_XEJUEYhE0s',
    appId: '1:802136451096:android:fab85ea091977d4e3d7b6d',
    messagingSenderId: '802136451096',
    projectId: 'couponchecker-406307',
    storageBucket: 'couponchecker-406307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRIaAiyPZSWQ_puXrWv4wGOqF1tb9VmY',
    appId: '1:802136451096:ios:5959625cef4a6d6c3d7b6d',
    messagingSenderId: '802136451096',
    projectId: 'couponchecker-406307',
    storageBucket: 'couponchecker-406307.appspot.com',
    iosClientId: '802136451096-ko7qsa2dntm7vq417b9mfkaounlpkkbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.couponchecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRIaAiyPZSWQ_puXrWv4wGOqF1tb9VmY',
    appId: '1:802136451096:ios:5959625cef4a6d6c3d7b6d',
    messagingSenderId: '802136451096',
    projectId: 'couponchecker-406307',
    storageBucket: 'couponchecker-406307.appspot.com',
    iosClientId: '802136451096-ko7qsa2dntm7vq417b9mfkaounlpkkbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.couponchecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApe-9X7W4gt4q2n14qEkHeH2WVUPMxbXg',
    appId: '1:802136451096:web:e1a30c80946a417c3d7b6d',
    messagingSenderId: '802136451096',
    projectId: 'couponchecker-406307',
    authDomain: 'couponchecker-406307.firebaseapp.com',
    storageBucket: 'couponchecker-406307.appspot.com',
    measurementId: 'G-B6D73LCNTF',
  );

}